language: swift

script: xcodebuild -workspace TwitterSentiment.xcworkspace -scheme TwitterSentiment -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
script: xcodebuild test -workspace TwitterSentiment.xcworkspace -scheme TwitterSentiment -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
